### ISSUE TITLE
web_115_302_simple和life_list_monitor出现无法连接情况

### ISSUE THREAD

**Issue by NefelibataWU** [ChenyangGao/web-mount-packs#43]
描述：
web_115_302_simple和life_list_monitor我是放在容器中运行的，先是在测试的虚拟机上运行正常，之后将镜像打包到实际运行的机器上遇到了一个问题，就是在测试的虚拟机还开启的情况下一切正常，一旦关闭了虚拟机，实际运行的机器上的脚本就会无法连接上115，经过检查网络一切正常，能正常访问外网。

相关日志：
web_115_302_simple的
[2024-08-30 19:29:29,605] (ERROR) ➜ blacksheep.client.exceptions.ConnectionTimeout: Connection attempt timed out, to https://proapi.115.com. Current timeout setting: 10.0.

life_list_monitor的
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/./monitor/life_list_monitor.py", line 280, in main
    resp = client.life_list({"show_type": 0, "start_time": start_time, "end_time": end_time}, request=request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/p115/component/client.py", line 4129, in life_list
    return self.request(url=api, params=payload, async_=async_, **request_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/p115/component/client.py", line 417, in request
    return request(
           ^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3_request/__init__.py", line 70, in request
    resp = pool.request(
           ^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 136, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 183, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='life.115.com', port=443): Max retries exceeded with url: /api/1.0/web/1.0/life/life_list?start=0&limit=1000&show_type=0&end_time=1725017304&start_time=1725011200 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbc6195a790>, 'Connection to life.115.com timed out. (connect timeout=5)'))

**Comment by NefelibataWU** [comment]
忽略这个issue，是我环境的原因
