### ISSUE TITLE
0.0.9.8.4版本中的fs.move函数有bug

### ISSUE THREAD

**Issue by qiqiandfei** [ChenyangGao/web-mount-packs#53]
fs.move函数无法正常工作，调用方法以及错误提示如下：

调用方法：
client = P115Client(cookie)
client.fs.move("/云下载/test/222", "/云下载/test/3333")

报错信息：
Traceback (most recent call last):
  File "D:\Syncthing\yufei\Code\Python\115Bot\app\client_115.py", line 164, in <module>
    client.move_file("/云下载/test/222", "/云下载/test/3333")
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Syncthing\yufei\Code\Python\115Bot\app\client_115.py", line 116, in move_file
    response = self.client.fs.move(src, dst)
  File "D:\DevelopmenEnv\Python\Python3.13.0_64\Lib\site-packages\p115\component\fs.py", line 3245, in move
    return run_gen_step(gen_step, async_=async_)
  File "D:\DevelopmenEnv\Python\Python3.13.0_64\Lib\site-packages\iterutils\__init__.py", line 277, in run_gen_step
    ret = send(ret)
  File "D:\DevelopmenEnv\Python\Python3.13.0_64\Lib\site-packages\p115\component\fs.py", line 3228, in gen_step
    if any(a["id"] == src_id for a in dst_attr["path"].ancestors):
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'ancestors'

在上个版本中该函数正常工作~

**Comment by ChenyangGao** [comment]
好的，忘记改了

**Comment by ChenyangGao** [comment]
已修复，更新到0.0.8.9.6即可

**Comment by qiqiandfei** [comment]
感恩的心~
