### ISSUE TITLE
offline_service.remove doesn't work anymore

### ISSUE THREAD

**Issue by ohnggni** [ChenyangGao/web-mount-packs#56]
Hello. Thank you for sharing this great API, first.
Recently, offline_service.remove doesn't work anymore. I suspect this is because 115.com would change their API somehow.
Could you please kindly check the below and fix the issue?

Here is the part of my code.
`@app.route('/tasks/clear_completed', methods=['POST']) # 완료된 작업을 json파일에서 일괄 삭제하는 기능 수행
def clear_completed_tasks():
    all_tasks = offline_service.list()  # 모든 작업 가져오기
    for task in all_tasks:
        if task['status'] == 2:  # 상태 2는 완료된 작업을 나타냅니다.
            offline_service.remove(task['info_hash'])
            task_id = task['info_hash']
            remove_task_time(task_id)  # JSON 파일에서 해당 task_id 삭제
    return jsonify({'status': 'completed tasks cleared'})`

This is the error message from my app.py
`INFO:httpx:HTTP Request: POST https://lixian.115.com/lixian/?ct=lixian&ac=task_lists "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://115.com/?ct=offline&ac=space "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://lixian.115.com/lixianssp/?ac=task_del "HTTP/1.1 200 OK"
ERROR:app:Exception on /tasks/clear_completed [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/p115client/client.py", line 133, in json_loads
    return loads(content)
           ^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 457, in clear_completed_tasks
    offline_service.remove(task['info_hash'])
  File "/usr/local/lib/python3.11/site-packages/p115/component/offline.py", line 764, in remove
    return check_response(self.client.offline_remove( # type: ignore
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/p115client/client.py", line 7656, in offline_remove
    return self._offline_lixianssp_post("task_del", payload, async_=async_, **request_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/p115client/client.py", line 7278, in _offline_lixianssp_post
    return self.request(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/p115client/client.py", line 1446, in request
    return request(url=url, method=method, **request_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx_request/__init__.py", line 245, in request
    return request_sync(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx_request/__init__.py", line 125, in request_sync
    return parse(resp, resp.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/p115client/client.py", line 7270, in parse
    json = json_loads(content)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/p115client/client.py", line 135, in json_loads
    raise DataError(errno.ENODATA, content) from e
p115client.exception.DataError: [Errno 61] b'decode fail!'
INFO:werkzeug:100.108.5.10 - - [16/Nov/2024 07:14:57] "POST /tasks/clear_completed HTTP/1.1" 500 -`

**Comment by ChenyangGao** [comment]
好的，明天看一下

**Comment by wangzixin100** [comment]
我也是
ol = client.offline
ol.add('ed2k://|file|Day.and.Night.2024.S02E21.HD1080P.X264.AAC.Mandarin.CHS.XLYS.mp4|300400990|741363fe8c299556c84c007424db09ff|/',savepath="/")

报错：
`JSONDecodeError                           Traceback (most recent call last)
File ~\Envs\115\Lib\site-packages\p115client\client.py:163, in json_loads(content)
    162 try:
--> 163     return loads(content)
    164 except Exception as e:

JSONDecodeError: unexpected character: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

DataError                                 Traceback (most recent call last)
Cell In[17], line 1
----> 1 ol.add('ed2k://|file|Day.and.Night.2024.S02E21.HD1080P.X264.AAC.Mandarin.CHS.XLYS.mp4|300400990|741363fe8c299556c84c007424db09ff|/',savepath="/")

File ~\Envs\115\Lib\site-packages\p115\component\offline.py:204, in P115Offline.add(self, urls, pid, savepath, async_)
    202 if savepath:
    203     payload["savepath"] = savepath
--> 204 return check_response(method( # type: ignore
    205     payload, 
    206     request=self.async_request if async_ else self.request, 
    207     async_=async_, 
    208 ))

File ~\Envs\115\Lib\site-packages\p115client\client.py:8327, in P115Client.offline_add_url(self, payload, async_, **request_kwargs)
   8325 if isinstance(payload, str):
   8326     payload = {"url": payload}
-> 8327 return self._offline_lixianssp_post("add_task_url", payload, async_=async_, **request_kwargs)

File ~\Envs\115\Lib\site-packages\p115client\client.py:8244, in P115Client._offline_lixianssp_post(self, ac, payload, async_, **request_kwargs)
   8242     return json
   8243 request_kwargs.setdefault("parse", parse)
-> 8244 return self.request(
   8245     url=api, 
   8246     method="POST", 
   8247     data={"data": rsa_encode(dumps(payload)).decode("ascii")}, 
   8248     async_=async_, 
   8249     **request_kwargs, 
   8250 )

File ~\Envs\115\Lib\site-packages\p115client\client.py:1969, in P115Client.request(self, url, method, params, async_, request, **request_kwargs)
   1967                             self.login_another_app(replace=True)
   1968 else:
-> 1969     return request(url=url, method=method, **request_kwargs)

File ~\Envs\115\Lib\site-packages\httpx_request\__init__.py:225, in request(url, method, parse, raise_for_status, session, async_, **request_kwargs)
    216     return request_async(
    217         url=url, 
    218         method=method, 
   (...)
    222         **request_kwargs, 
    223     )
    224 else:
--> 225     return request_sync(
    226         url=url, 
    227         method=method, 
    228         parse=parse, 
    229         raise_for_status=raise_for_status, 
    230         session=cast(None | Client, session), 
    231         **request_kwargs, 
    232     )

File ~\Envs\115\Lib\site-packages\httpx_request\__init__.py:117, in request_sync(url, method, parse, raise_for_status, session, auth, follow_redirects, stream, **request_kwargs)
    115     return parse(resp)
    116 else:
--> 117     return parse(resp, resp.read())

File ~\Envs\115\Lib\site-packages\p115client\client.py:8236, in P115Client._offline_lixianssp_post.<locals>.parse(resp, content)
   8235 def parse(resp, content: bytes) -> dict:
-> 8236     json = json_loads(content)
   8237     if data := json.get("data"):
   8238         try:

File ~\Envs\115\Lib\site-packages\p115client\client.py:165, in json_loads(content)
    163     return loads(content)
    164 except Exception as e:
--> 165     raise DataError(errno.ENODATA, content) from e

DataError: [Errno 120] b'decode fail!'`

**Comment by ChenyangGao** [comment]
solved
```console
pip install -U 'python-115>=python-115-0.0.9.8.8'
```

**Comment by ohnggni** [comment]
> solved
> 
> ```
> pip install -U 'python-115>=0.0.9.8.8'
> ```

It works well. Thanks!
