### ISSUE TITLE
运行wish相关函数时http error 405

### ISSUE THREAD

**Issue by ggvisPro** [ChenyangGao/web-mount-packs#63]
以下是完整的错误提示：
======= RESTART: /Users/ZhikunWang/Desktop/VSCode/Python/115/115_wish.py =======
Traceback (most recent call last):
  File "/Users/ZhikunWang/Desktop/VSCode/Python/115/115_wish.py", line 282, in <module>
    cookie_more_5GB = {key: value for key, value in cookie_all.items() if wish_remain(key, value)[1] > 0} # 筛选出大于5GB的心愿数量的账号出大于5GB的心愿数量的账号
  File "/Users/ZhikunWang/Desktop/VSCode/Python/115/115_wish.py", line 203, in wish_remain
    wishes = wish_list(cookie, type=1) # 计算本次执行完成后的未完成心愿数量，以及大于5GB的心愿数量
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/p115client/tool/xys.py", line 74, in wish_list
    ls = adds = check_response(client.act_xys_my_desire(payload))["data"]["list"]
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/p115client/client.py", line 2444, in act_xys_my_desire
    return self.request(url=api, params=payload, async_=async_, **request_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/p115client/client.py", line 2092, in request
    return request(url=url, method=method, **request_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/httpx_request/__init__.py", line 225, in request
    return request_sync(
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/httpx_request/__init__.py", line 93, in request_sync
    resp.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '405 Not Allowed' for url 'https://act.115.com/api/1.0/web/1.0/act2024xys/my_desire?type=1&start=0&page=1&limit=1000'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

**Comment by ChenyangGao** [comment]
升级到最新版p115client
